2020-08-13 13:52:21,741 - INFO - Snowflake Connector for Python Version: 2.2.10, Python Version: 3.8.2, Platform: Windows-10-10.0.17763-SP0
2020-08-13 13:52:21,742 - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
2020-08-13 13:52:21,742 - INFO - Setting use_openssl_only mode to False
2020-08-13 13:52:23,329 - INFO - Deleting table data: KAMALA_ORDER_DETAIL
2020-08-13 13:52:23,329 - INFO - query: [delete from KAMALA_ORDER_DETAIL]
2020-08-13 13:52:23,699 - INFO - query execution done
2020-08-13 13:52:23,699 - INFO - query: [select appointment_id, row_number() over (order by appointment_id) rn, count(*) ...]
2020-08-13 13:52:24,032 - INFO - query execution done
2020-08-13 13:52:25,422 - INFO - Requesting page 1 of 20528
2020-08-13 13:52:25,422 - INFO - order_id: 1416270
2020-08-13 13:52:26,150 - INFO - Writing page 1 of 20528 to SnowFlake
2020-08-13 13:52:26,151 - INFO - query: [merge into KAMALA_ORDER_DETAIL t using (select parse_json('{"id": 1416270, "acco...]
2020-08-13 13:52:26,610 - INFO - query execution done
2020-08-13 13:52:26,610 - ERROR - https://klientiks.ru/clientix/Restapi/getAppointment/a/390b96e2763e/u/d969c9cde78c/t/073de5009f21b34afa022cfa7ca2c124/id/1416270Page 1 of 20528 failed
Traceback (most recent call last):
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx2sf.py", line 66, in flush_kamala_order_detail
    mrg_to_table(ctx, table_name, response)
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\sf.py", line 28, in mrg_to_table
    cs.execute(l_sql)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 594, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 123, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 83, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100069 (22P02): 019637ec-024c-4076-0003-e0030047c736: Error parsing JSON: missing comma, pos 1740
2020-08-13 13:52:26,612 - INFO - Requesting page 2 of 20528
2020-08-13 13:52:26,612 - INFO - order_id: 1416271
2020-08-13 13:52:27,032 - INFO - Writing page 2 of 20528 to SnowFlake
2020-08-13 13:52:27,033 - INFO - query: [merge into KAMALA_ORDER_DETAIL t using (select parse_json('{"id": 1416271, "acco...]
2020-08-13 13:52:28,411 - INFO - query execution done
2020-08-13 13:52:28,411 - ERROR - https://klientiks.ru/clientix/Restapi/getAppointment/a/390b96e2763e/u/d969c9cde78c/t/073de5009f21b34afa022cfa7ca2c124/id/1416271Page 2 of 20528 failed
Traceback (most recent call last):
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx2sf.py", line 66, in flush_kamala_order_detail
    mrg_to_table(ctx, table_name, response)
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\sf.py", line 28, in mrg_to_table
    cs.execute(l_sql)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 594, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 123, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 83, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100069 (22P02): 019637ec-021e-e2d9-0003-e0030047d70a: Error parsing JSON: missing comma, pos 1754
2020-08-13 13:52:28,412 - INFO - Requesting page 3 of 20528
2020-08-13 13:52:28,412 - INFO - order_id: 1416272
2020-08-13 13:52:28,785 - INFO - Writing page 3 of 20528 to SnowFlake
2020-08-13 13:52:28,786 - INFO - query: [merge into KAMALA_ORDER_DETAIL t using (select parse_json('{"id": 1416272, "acco...]
2020-08-13 13:52:29,203 - INFO - query execution done
2020-08-13 13:52:29,203 - ERROR - https://klientiks.ru/clientix/Restapi/getAppointment/a/390b96e2763e/u/d969c9cde78c/t/073de5009f21b34afa022cfa7ca2c124/id/1416272Page 3 of 20528 failed
Traceback (most recent call last):
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx2sf.py", line 66, in flush_kamala_order_detail
    mrg_to_table(ctx, table_name, response)
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\sf.py", line 28, in mrg_to_table
    cs.execute(l_sql)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 594, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 123, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 83, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100069 (22P02): 019637ec-022f-462f-0003-e0030047c73a: Error parsing JSON: missing comma, pos 1729
2020-08-13 13:52:29,204 - INFO - Requesting page 4 of 20528
2020-08-13 13:52:29,204 - INFO - order_id: 1416273
2020-08-13 13:52:29,501 - INFO - Writing page 4 of 20528 to SnowFlake
2020-08-13 13:52:29,501 - INFO - query: [merge into KAMALA_ORDER_DETAIL t using (select parse_json('{"id": 1416273, "acco...]
2020-08-13 13:52:29,956 - INFO - query execution done
2020-08-13 13:52:29,956 - ERROR - https://klientiks.ru/clientix/Restapi/getAppointment/a/390b96e2763e/u/d969c9cde78c/t/073de5009f21b34afa022cfa7ca2c124/id/1416273Page 4 of 20528 failed
Traceback (most recent call last):
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx2sf.py", line 66, in flush_kamala_order_detail
    mrg_to_table(ctx, table_name, response)
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\sf.py", line 28, in mrg_to_table
    cs.execute(l_sql)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 594, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 123, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 83, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100069 (22P02): 019637ec-0264-7585-0003-e0030047d70e: Error parsing JSON: missing comma, pos 1766
2020-08-13 13:52:29,957 - INFO - Requesting page 5 of 20528
2020-08-13 13:52:29,957 - INFO - order_id: 1416274
2020-08-13 13:52:30,273 - INFO - Writing page 5 of 20528 to SnowFlake
2020-08-13 13:52:30,273 - INFO - query: [merge into KAMALA_ORDER_DETAIL t using (select parse_json('{"id": 1416274, "acco...]
2020-08-13 13:52:30,685 - INFO - query execution done
2020-08-13 13:52:30,685 - ERROR - https://klientiks.ru/clientix/Restapi/getAppointment/a/390b96e2763e/u/d969c9cde78c/t/073de5009f21b34afa022cfa7ca2c124/id/1416274Page 5 of 20528 failed
Traceback (most recent call last):
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx2sf.py", line 66, in flush_kamala_order_detail
    mrg_to_table(ctx, table_name, response)
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\sf.py", line 28, in mrg_to_table
    cs.execute(l_sql)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 594, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 123, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 83, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100069 (22P02): 019637ec-02e2-8383-0003-e0030047c73e: Error parsing JSON: missing comma, pos 1729
2020-08-13 13:52:30,686 - INFO - Requesting page 6 of 20528
2020-08-13 13:52:30,686 - INFO - order_id: 1416275
2020-08-13 13:52:30,948 - INFO - Writing page 6 of 20528 to SnowFlake
2020-08-13 13:52:30,949 - INFO - query: [merge into KAMALA_ORDER_DETAIL t using (select parse_json('{"id": 1416275, "acco...]
2020-08-13 13:52:31,399 - INFO - query execution done
2020-08-13 13:52:31,399 - ERROR - https://klientiks.ru/clientix/Restapi/getAppointment/a/390b96e2763e/u/d969c9cde78c/t/073de5009f21b34afa022cfa7ca2c124/id/1416275Page 6 of 20528 failed
Traceback (most recent call last):
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx2sf.py", line 66, in flush_kamala_order_detail
    mrg_to_table(ctx, table_name, response)
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\sf.py", line 28, in mrg_to_table
    cs.execute(l_sql)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 594, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 123, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 83, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100069 (22P02): 019637ec-021d-f80e-0003-e0030047d712: Error parsing JSON: missing comma, pos 1729
2020-08-13 13:52:31,400 - INFO - Requesting page 7 of 20528
2020-08-13 13:52:31,400 - INFO - order_id: 1416276
2020-08-13 13:52:31,782 - INFO - Writing page 7 of 20528 to SnowFlake
2020-08-13 13:52:31,782 - INFO - query: [merge into KAMALA_ORDER_DETAIL t using (select parse_json('{"id": 1416276, "acco...]
2020-08-13 13:52:32,199 - INFO - query execution done
2020-08-13 13:52:32,200 - ERROR - https://klientiks.ru/clientix/Restapi/getAppointment/a/390b96e2763e/u/d969c9cde78c/t/073de5009f21b34afa022cfa7ca2c124/id/1416276Page 7 of 20528 failed
Traceback (most recent call last):
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx2sf.py", line 66, in flush_kamala_order_detail
    mrg_to_table(ctx, table_name, response)
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\sf.py", line 28, in mrg_to_table
    cs.execute(l_sql)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 594, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 123, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 83, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100069 (22P02): 019637ec-02b7-6c1a-0003-e0030047c742: Error parsing JSON: missing comma, pos 1742
2020-08-13 13:52:32,201 - INFO - Requesting page 8 of 20528
2020-08-13 13:52:32,202 - INFO - order_id: 1416277
2020-08-13 13:52:32,599 - INFO - Writing page 8 of 20528 to SnowFlake
2020-08-13 13:52:32,600 - INFO - query: [merge into KAMALA_ORDER_DETAIL t using (select parse_json('{"id": 1416277, "acco...]
2020-08-13 13:52:33,013 - INFO - query execution done
2020-08-13 13:52:33,013 - ERROR - https://klientiks.ru/clientix/Restapi/getAppointment/a/390b96e2763e/u/d969c9cde78c/t/073de5009f21b34afa022cfa7ca2c124/id/1416277Page 8 of 20528 failed
Traceback (most recent call last):
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx2sf.py", line 66, in flush_kamala_order_detail
    mrg_to_table(ctx, table_name, response)
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\sf.py", line 28, in mrg_to_table
    cs.execute(l_sql)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 594, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 123, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 83, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100069 (22P02): 019637ec-0280-49e1-0003-e0030047c746: Error parsing JSON: missing comma, pos 1742
2020-08-13 13:52:33,014 - INFO - Requesting page 9 of 20528
2020-08-13 13:52:33,014 - INFO - order_id: 1416278
2020-08-13 13:52:33,359 - INFO - Writing page 9 of 20528 to SnowFlake
2020-08-13 13:52:33,359 - INFO - query: [merge into KAMALA_ORDER_DETAIL t using (select parse_json('{"id": 1416278, "acco...]
2020-08-13 13:52:33,802 - INFO - query execution done
2020-08-13 13:52:33,803 - ERROR - https://klientiks.ru/clientix/Restapi/getAppointment/a/390b96e2763e/u/d969c9cde78c/t/073de5009f21b34afa022cfa7ca2c124/id/1416278Page 9 of 20528 failed
Traceback (most recent call last):
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx2sf.py", line 66, in flush_kamala_order_detail
    mrg_to_table(ctx, table_name, response)
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\sf.py", line 28, in mrg_to_table
    cs.execute(l_sql)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 594, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 123, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 83, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100069 (22P02): 019637ec-0238-e22a-0003-e0030047d716: Error parsing JSON: missing comma, pos 1754
2020-08-13 13:52:33,807 - INFO - Requesting page 10 of 20528
2020-08-13 13:52:33,807 - INFO - order_id: 1416279
2020-08-13 13:52:34,138 - INFO - Writing page 10 of 20528 to SnowFlake
2020-08-13 13:52:34,138 - INFO - query: [merge into KAMALA_ORDER_DETAIL t using (select parse_json('{"id": 1416279, "acco...]
2020-08-13 13:52:34,576 - INFO - query execution done
2020-08-13 13:52:34,577 - ERROR - https://klientiks.ru/clientix/Restapi/getAppointment/a/390b96e2763e/u/d969c9cde78c/t/073de5009f21b34afa022cfa7ca2c124/id/1416279Page 10 of 20528 failed
Traceback (most recent call last):
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx2sf.py", line 66, in flush_kamala_order_detail
    mrg_to_table(ctx, table_name, response)
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\sf.py", line 28, in mrg_to_table
    cs.execute(l_sql)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 594, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 123, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 83, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100069 (22P02): 019637ec-02fc-1912-0003-e0030047d71a: Error parsing JSON: missing comma, pos 1754
2020-08-13 13:52:34,577 - INFO - Requesting page 11 of 20528
2020-08-13 13:52:34,577 - INFO - order_id: 1416280
2020-08-13 13:52:34,982 - INFO - Writing page 11 of 20528 to SnowFlake
2020-08-13 13:52:34,982 - INFO - query: [merge into KAMALA_ORDER_DETAIL t using (select parse_json('{"id": 1416280, "acco...]
2020-08-13 13:52:35,429 - INFO - query execution done
2020-08-13 13:52:35,429 - ERROR - https://klientiks.ru/clientix/Restapi/getAppointment/a/390b96e2763e/u/d969c9cde78c/t/073de5009f21b34afa022cfa7ca2c124/id/1416280Page 11 of 20528 failed
Traceback (most recent call last):
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx2sf.py", line 66, in flush_kamala_order_detail
    mrg_to_table(ctx, table_name, response)
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\sf.py", line 28, in mrg_to_table
    cs.execute(l_sql)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 594, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 123, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 83, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100069 (22P02): 019637ec-02aa-ebb8-0003-e0030047d71e: Error parsing JSON: missing comma, pos 1841
2020-08-13 13:52:35,432 - INFO - Requesting page 12 of 20528
2020-08-13 13:52:35,432 - INFO - order_id: 1416281
2020-08-13 13:52:35,818 - INFO - Writing page 12 of 20528 to SnowFlake
2020-08-13 13:52:35,820 - INFO - query: [merge into KAMALA_ORDER_DETAIL t using (select parse_json('{"id": 1416281, "acco...]
2020-08-13 13:52:36,255 - INFO - query execution done
2020-08-13 13:52:36,256 - ERROR - https://klientiks.ru/clientix/Restapi/getAppointment/a/390b96e2763e/u/d969c9cde78c/t/073de5009f21b34afa022cfa7ca2c124/id/1416281Page 12 of 20528 failed
Traceback (most recent call last):
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx2sf.py", line 66, in flush_kamala_order_detail
    mrg_to_table(ctx, table_name, response)
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\sf.py", line 28, in mrg_to_table
    cs.execute(l_sql)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 594, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 123, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 83, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100069 (22P02): 019637ec-0241-20f1-0003-e0030047c74a: Error parsing JSON: missing comma, pos 1849
2020-08-13 13:52:36,259 - INFO - Requesting page 13 of 20528
2020-08-13 13:52:36,259 - INFO - order_id: 1416282
2020-08-13 13:52:36,615 - INFO - Writing page 13 of 20528 to SnowFlake
2020-08-13 13:52:36,615 - INFO - query: [merge into KAMALA_ORDER_DETAIL t using (select parse_json('{"id": 1416282, "acco...]
2020-08-13 13:52:37,073 - INFO - query execution done
2020-08-13 13:52:37,073 - ERROR - https://klientiks.ru/clientix/Restapi/getAppointment/a/390b96e2763e/u/d969c9cde78c/t/073de5009f21b34afa022cfa7ca2c124/id/1416282Page 13 of 20528 failed
Traceback (most recent call last):
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx2sf.py", line 66, in flush_kamala_order_detail
    mrg_to_table(ctx, table_name, response)
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\sf.py", line 28, in mrg_to_table
    cs.execute(l_sql)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 594, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 123, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 83, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100069 (22P02): 019637ec-02e9-44dc-0003-e0030047d722: Error parsing JSON: missing comma, pos 1703
2020-08-13 13:52:37,074 - INFO - Requesting page 14 of 20528
2020-08-13 13:52:37,074 - INFO - order_id: 1416283
2020-08-13 13:52:37,503 - INFO - Writing page 14 of 20528 to SnowFlake
2020-08-13 13:52:37,503 - INFO - query: [merge into KAMALA_ORDER_DETAIL t using (select parse_json('{"id": 1416283, "acco...]
2020-08-13 13:52:38,187 - INFO - query execution done
2020-08-13 13:52:38,187 - ERROR - https://klientiks.ru/clientix/Restapi/getAppointment/a/390b96e2763e/u/d969c9cde78c/t/073de5009f21b34afa022cfa7ca2c124/id/1416283Page 14 of 20528 failed
Traceback (most recent call last):
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx2sf.py", line 66, in flush_kamala_order_detail
    mrg_to_table(ctx, table_name, response)
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\sf.py", line 28, in mrg_to_table
    cs.execute(l_sql)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 594, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 123, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 83, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100069 (22P02): 019637ec-02ed-321b-0003-e0030047d726: Error parsing JSON: missing comma, pos 1651
2020-08-13 13:52:38,188 - INFO - Requesting page 15 of 20528
2020-08-13 13:52:38,188 - INFO - order_id: 1416284
2020-08-13 13:52:38,489 - INFO - Writing page 15 of 20528 to SnowFlake
2020-08-13 13:52:38,489 - INFO - query: [merge into KAMALA_ORDER_DETAIL t using (select parse_json('{"id": 1416284, "acco...]
2020-08-13 13:52:38,946 - INFO - query execution done
2020-08-13 13:52:38,946 - ERROR - https://klientiks.ru/clientix/Restapi/getAppointment/a/390b96e2763e/u/d969c9cde78c/t/073de5009f21b34afa022cfa7ca2c124/id/1416284Page 15 of 20528 failed
Traceback (most recent call last):
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx2sf.py", line 66, in flush_kamala_order_detail
    mrg_to_table(ctx, table_name, response)
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\sf.py", line 28, in mrg_to_table
    cs.execute(l_sql)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 594, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 123, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 83, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100069 (22P02): 019637ec-0235-a393-0003-e0030047c74e: Error parsing JSON: missing comma, pos 1827
2020-08-13 13:52:38,947 - INFO - Requesting page 16 of 20528
2020-08-13 13:52:38,947 - INFO - order_id: 1416285
2020-08-13 13:52:39,247 - INFO - Writing page 16 of 20528 to SnowFlake
2020-08-13 13:52:39,248 - INFO - query: [merge into KAMALA_ORDER_DETAIL t using (select parse_json('{"id": 1416285, "acco...]
2020-08-13 13:52:39,803 - INFO - query execution done
2020-08-13 13:52:39,803 - ERROR - https://klientiks.ru/clientix/Restapi/getAppointment/a/390b96e2763e/u/d969c9cde78c/t/073de5009f21b34afa022cfa7ca2c124/id/1416285Page 16 of 20528 failed
Traceback (most recent call last):
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx2sf.py", line 66, in flush_kamala_order_detail
    mrg_to_table(ctx, table_name, response)
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\sf.py", line 28, in mrg_to_table
    cs.execute(l_sql)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 594, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 123, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 83, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100069 (22P02): 019637ec-02a2-eb59-0003-e0030047c752: Error parsing JSON: missing comma, pos 1643
2020-08-13 13:52:39,804 - INFO - Requesting page 17 of 20528
2020-08-13 13:52:39,804 - INFO - order_id: 1416286
2020-08-13 13:52:40,127 - INFO - Writing page 17 of 20528 to SnowFlake
2020-08-13 13:52:40,128 - INFO - query: [merge into KAMALA_ORDER_DETAIL t using (select parse_json('{"id": 1416286, "acco...]
2020-08-13 13:52:40,585 - INFO - query execution done
2020-08-13 13:52:40,586 - ERROR - https://klientiks.ru/clientix/Restapi/getAppointment/a/390b96e2763e/u/d969c9cde78c/t/073de5009f21b34afa022cfa7ca2c124/id/1416286Page 17 of 20528 failed
Traceback (most recent call last):
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx2sf.py", line 66, in flush_kamala_order_detail
    mrg_to_table(ctx, table_name, response)
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\sf.py", line 28, in mrg_to_table
    cs.execute(l_sql)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 594, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 123, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 83, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100069 (22P02): 019637ec-0240-16bb-0003-e0030047d72a: Error parsing JSON: missing comma, pos 1804
2020-08-13 13:52:40,587 - INFO - Requesting page 18 of 20528
2020-08-13 13:52:40,587 - INFO - order_id: 1416287
2020-08-13 13:52:40,958 - INFO - Writing page 18 of 20528 to SnowFlake
2020-08-13 13:52:40,959 - INFO - query: [merge into KAMALA_ORDER_DETAIL t using (select parse_json('{"id": 1416287, "acco...]
2020-08-13 13:52:41,448 - INFO - query execution done
2020-08-13 13:52:41,448 - ERROR - https://klientiks.ru/clientix/Restapi/getAppointment/a/390b96e2763e/u/d969c9cde78c/t/073de5009f21b34afa022cfa7ca2c124/id/1416287Page 18 of 20528 failed
Traceback (most recent call last):
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx2sf.py", line 66, in flush_kamala_order_detail
    mrg_to_table(ctx, table_name, response)
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\sf.py", line 28, in mrg_to_table
    cs.execute(l_sql)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 594, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 123, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 83, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100069 (22P02): 019637ec-02c5-ca9c-0003-e0030047d736: Error parsing JSON: missing comma, pos 1623
2020-08-13 13:52:41,449 - INFO - Requesting page 19 of 20528
2020-08-13 13:52:41,449 - INFO - order_id: 1416288
2020-08-13 13:52:41,730 - INFO - Writing page 19 of 20528 to SnowFlake
2020-08-13 13:52:41,730 - INFO - query: [merge into KAMALA_ORDER_DETAIL t using (select parse_json('{"id": 1416288, "acco...]
2020-08-13 13:52:42,176 - INFO - query execution done
2020-08-13 13:52:42,176 - ERROR - https://klientiks.ru/clientix/Restapi/getAppointment/a/390b96e2763e/u/d969c9cde78c/t/073de5009f21b34afa022cfa7ca2c124/id/1416288Page 19 of 20528 failed
Traceback (most recent call last):
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx2sf.py", line 66, in flush_kamala_order_detail
    mrg_to_table(ctx, table_name, response)
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\sf.py", line 28, in mrg_to_table
    cs.execute(l_sql)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 594, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 123, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\errors.py", line 83, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100069 (22P02): 019637ec-0228-6a96-0003-e0030047d73a: Error parsing JSON: missing comma, pos 1623
2020-08-13 13:52:42,177 - INFO - Requesting page 20 of 20528
2020-08-13 13:52:42,177 - INFO - order_id: 1416289
2020-08-13 13:52:42,229 - ERROR - https://klientiks.ru/clientix/Restapi/getAppointment/a/390b96e2763e/u/d969c9cde78c/t/073de5009f21b34afa022cfa7ca2c124/id/1416289Page 20 of 20528 failed
Traceback (most recent call last):
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx2sf.py", line 64, in flush_kamala_order_detail
    response = get_data_chunk(API_ORDER_DETAIL, appointment_id)
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx.py", line 24, in get_data_chunk
    r = requests.get(url=(api_endpoint + str(offset)))
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connection.py", line 352, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\ssl_wrap_socket.py", line 401, in ssl_wrap_socket_with_ocsp
    v = SFOCSP(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\ocsp_asn1crypto.py", line 65, in __init__
    super(SnowflakeOCSPAsn1Crypto, self).__init__(**kwargs)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\ocsp_snowflake.py", line 902, in __init__
    SnowflakeOCSP.OCSP_CACHE.read_file(self)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\ocsp_snowflake.py", line 410, in read_file
    OCSPCache.read_ocsp_response_cache_file(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\ocsp_snowflake.py", line 432, in read_ocsp_response_cache_file
    ocsp.decode_ocsp_response_cache(json.load(f))
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\ocsp_snowflake.py", line 1451, in decode_ocsp_response_cache
    SnowflakeOCSP.OCSP_CACHE.update_or_delete_cache(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\ocsp_snowflake.py", line 589, in update_or_delete_cache
    found, _ = OCSPCache.find_cache(ocsp, cert_id, None)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\ocsp_snowflake.py", line 555, in find_cache
    ocsp.is_valid_time(cert_id, cache):
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\ocsp_asn1crypto.py", line 191, in is_valid_time
    if basic_ocsp_response['certs'].native:
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\asn1crypto\core.py", line 4503, in native
    self._parse_children(recurse=True)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\asn1crypto\core.py", line 4469, in _parse_children
    child._parse_children(recurse=True)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\asn1crypto\core.py", line 3940, in _parse_children
    child._parse_children(recurse=True)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\asn1crypto\core.py", line 3940, in _parse_children
    child._parse_children(recurse=True)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\asn1crypto\core.py", line 4469, in _parse_children
    child._parse_children(recurse=True)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\asn1crypto\core.py", line 3938, in _parse_children
    child = _build(*child)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\asn1crypto\core.py", line 5606, in _build
    value.parse(nested_spec)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\asn1crypto\core.py", line 2792, in parse
    parsed_value, _ = _parse_build(self.__bytes__(), spec=spec, spec_params=spec_params)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\asn1crypto\core.py", line 5646, in _parse_build
    info, new_pointer = _parse(encoded_data, encoded_len, pointer)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\asn1crypto\parser.py", line 232, in _parse
    encoded_data[pointer:contents_end],
KeyboardInterrupt
2020-08-13 13:52:42,246 - INFO - Requesting page 21 of 20528
2020-08-13 13:52:42,246 - INFO - order_id: 1416290
2020-08-13 13:52:42,602 - INFO - Writing page 21 of 20528 to SnowFlake
2020-08-13 13:52:42,602 - INFO - query: [merge into KAMALA_ORDER_DETAIL t using (select parse_json('{"id": 1416290, "acco...]
2020-08-13 13:52:43,360 - INFO - Force exit
2020-08-13 13:52:43,361 - ERROR - https://klientiks.ru/clientix/Restapi/getAppointment/a/390b96e2763e/u/d969c9cde78c/t/073de5009f21b34afa022cfa7ca2c124/id/1416290Page 21 of 20528 failed
Traceback (most recent call last):
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\kx2sf.py", line 66, in flush_kamala_order_detail
    mrg_to_table(ctx, table_name, response)
  File "C:\Users\dmitry.mitrofanov\codebase\kamala\kamala\sf.py", line 28, in mrg_to_table
    cs.execute(l_sql)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 523, in execute
    ret = self._execute_helper(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 374, in _execute_helper
    ret = self._connection.cmd_query(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\connection.py", line 813, in cmd_query
    ret = self.rest.request(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\network.py", line 287, in request
    return self._post_request(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\network.py", line 488, in _post_request
    ret = self.fetch('post', full_url, headers, data=body,
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\network.py", line 566, in fetch
    ret = self._request_exec_wrapper(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\network.py", line 599, in _request_exec_wrapper
    return_object = self._request_exec(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\network.py", line 754, in _request_exec
    raw_ret = session.request(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\contrib\pyopenssl.py", line 325, in recv_into
    if not util.wait_for_read(self.socket, self.socket.gettimeout()):
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\wait.py", line 146, in wait_for_read
    return wait_for_socket(sock, read=True, timeout=timeout)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\wait.py", line 86, in select_wait_for_socket
    rready, wready, xready = _retry_on_intr(fn, timeout)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\wait.py", line 43, in _retry_on_intr
    return fn(timeout)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 355, in interrupt_handler
    self.__cancel_query(query)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 888, in __cancel_query
    self._connection._cancel_query(query, self._request_id)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\connection.py", line 997, in _cancel_query
    return self.rest.request(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\network.py", line 287, in request
    return self._post_request(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\network.py", line 488, in _post_request
    ret = self.fetch('post', full_url, headers, data=body,
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\network.py", line 566, in fetch
    ret = self._request_exec_wrapper(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\network.py", line 599, in _request_exec_wrapper
    return_object = self._request_exec(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\network.py", line 754, in _request_exec
    raw_ret = session.request(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\contrib\pyopenssl.py", line 325, in recv_into
    if not util.wait_for_read(self.socket, self.socket.gettimeout()):
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\wait.py", line 146, in wait_for_read
    return wait_for_socket(sock, read=True, timeout=timeout)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\wait.py", line 86, in select_wait_for_socket
    rready, wready, xready = _retry_on_intr(fn, timeout)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\wait.py", line 43, in _retry_on_intr
    return fn(timeout)
  File "C:\Users\dmitry.mitrofanov\AppData\Local\Programs\Python\Python38-32\lib\site-packages\snowflake\connector\cursor.py", line 77, in exit_handler
    sys.exit(1)
SystemExit: 1
2020-08-13 13:52:43,366 - INFO - Requesting page 22 of 20528
2020-08-13 13:52:43,366 - INFO - order_id: 1416291
2020-08-13 13:52:43,642 - INFO - Writing page 22 of 20528 to SnowFlake
2020-08-13 13:52:43,643 - INFO - query: [merge into KAMALA_ORDER_DETAIL t using (select parse_json('{"id": 1416291, "acco...]
2020-08-13 13:52:45,184 - INFO - Force exit
